name: Linux

on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  build-docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        tags: ghcr.io/ltowarek/lingua-linux-devcontainer
        file: ./.devcontainer/linux/Dockerfile
        push: true

  run-checks:
    needs: build-docker
    permissions:
      contents: read

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ltowarek/lingua-linux-devcontainer
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -S . -G Ninja -DCMAKE_TOOLCHAIN_FILE:STRING=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake -DANTLR4_JAR_LOCATION:STRING=$ANTLR4_JAR_LOCATION

    - name: Build
      run: cmake --build build --parallel
